export const userRegister = "/auth/signup"
export const userLogin = "/auth/login"
export const fetchUser = "/auth/fetchuser"
export const trade = "/api/trade"
export const fetchPortfolio = "/api/fetchPortfolio"
export const squareOffPort = "/api/squareOff"